# Generated by Django 5.1.1 on 2024-09-15 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Description')),
                ('status', models.CharField(max_length=250, verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=250, verbose_name='Month')),
                ('status', models.CharField(max_length=250, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='invoice.basicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Investiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranca2', to='invoice.billing')),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('required', models.BooleanField(verbose_name='Fixo')),
                ('bank', models.CharField(max_length=250, verbose_name='Bank')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranca', to='invoice.billing')),
            ],
        ),
    ]
