# Generated by Django 5.1.1 on 2024-09-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salary'),
            preserve_default=False,
        ),
    ]
