# Generated by Django 5.1.1 on 2024-09-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_basicdata_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicdata',
            name='name',
        ),
    ]
